# Type stubs for cv2
from typing import Any, Tuple

INTER_AREA: int = 3
CV_32F: int = 5
TM_CCOEFF_NORMED: int = 5

def resize(src: Any, dsize: Tuple[int, int], interpolation: int = ...) -> Any: ...
def Sobel(src: Any, ddepth: int, dx: int, dy: int, ksize: int = ...) -> Any: ...
def magnitude(x: Any, y: Any) -> Any: ...
def GaussianBlur(src: Any, ksize: Tuple[int, int], sigmaX: float, sigmaY: float = ...) -> Any: ...
def matchTemplate(image: Any, templ: Any, method: int) -> Any: ...
def minMaxLoc(src: Any) -> Tuple[float, float, Tuple[int, int], Tuple[int, int]]: ...
